services:
  chat_backend:
    container_name: chat_backend
    build:
      context: .
      dockerfile: Dockerfile  # Use the correct Dockerfile without a target
    ports:
      - "3020:3020"
    env_file:
      - .env
    networks:
      - chat_server_network
    volumes:
      - .:/usr/src/app  # Corrected the mount to match the WORKDIR in Dockerfile
    restart: unless-stopped

networks:
  chat_server_network:
    driver: bridge
