version: '3.8'

services:
  chat_backend:
    container_name: chat_backend
    build:
      context: .
      dockerfile: Dockerfile  # Removed target since there's no multi-stage build
    ports:
      - "3020:3020"
    env_file:
      - .env
    networks:
      - chat_server_network
    volumes:
      - .:/app  # Mount the current directory (useful for development)
    restart: unless-stopped

networks:
  chat_server_network:
    driver: bridge
